SET IDENTITY_INSERT [dbo].[User] ON
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (1, N'1234567A', N'John', N'Lennon', N'jl@email.com', N'2018-01-15', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (2, N'234567B', N'Jack', N'Angel', N'jangel@email.com', N'2018-01-16', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (3, N'3456789F', N'Mary', N'Doe', N'md@email.com', N'2018-01-12', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (4, N'9566541K', N'Tom', N'Kelly', N'tk@email.com', N'2018-01-10', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (5, N'5124567F', N'Angie', N'Lotts', N'al@email.com', N'2018-01-11', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (6, N'6547890F', N'Aiofe', N'Hearney', N'ah@email.com', N'2018-01-19', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (7, N'6547890F', N'Aiofe', N'Hearney', N'ah@email.com', N'2018-01-22', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (8, N'6547890F', N'Aiofe', N'Hearney', N'ah@email.com', N'2018-01-22', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (9, N'4105236H', N'Sammie', N'Smith', N'sas@email.com', N'2018-01-17', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (10, N'4111111L', N'Sophie', N'Andrews', N'sa@email.com', N'2018-01-23', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (11, N'2225566J', N'Sarah', N'Manna', N'sm@email.com', N'2018-01-24', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (12, N'2468111A', N'Osasere', N'Ogiehor', N'oo@email.com', N'2018-02-02', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (13, N'2222333D', N'Chisom', N'Ogiehor', N'co@gmail.com', N'2018-03-26', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (14, N'8529632F', N'Ela', N'Markle', N'em@email.com', N'2018-01-30', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (15, N'8529632F', N'Ela', N'Markle', N'em@email.com', N'2018-01-30', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (16, N'4445555M', N'Marcus', N'Alonso', N'ma@email.com', N'2018-01-23', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (17, N'5554444F', N'Alice', N'Burke', N'ab@email.com', N'2018-01-23', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (18, N'9995566K', N'Maria', N'Kelly', N'mk@gmail.com', N'2018-01-23', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (19, N'2200220N', N'Isabel', N'Song', N'is@email.com', N'2018-01-23', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (20, N'2133665I', N'Claire', N'Button', N'cb@email.com', N'2018-01-22', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (21, N'4445555M', N'Maria', N'Kelly', N'mk@gmail.com', N'2018-01-17', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (22, N'1111111K', N'Adam', N'Adam', N'aa@email.com', N'2018-01-24', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (23, N'1111111K', N'Adam', N'Adam', N'aa@email.com', N'2018-01-24', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (24, N'1111111K', N'Adam', N'Adam', N'aa@email.com', N'2018-01-24', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (25, N'1234567A', N'Adam', N'Alonso', N'aa@email.com', N'2018-01-25', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (26, N'7412589J', N'Noreen', N'Smith', N'ns@email.com', N'2018-01-19', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (27, N'3698521U', N'Maggie', N'Richards', N'mr@email.com', N'2018-01-12', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (28, N'7418523T', N'Aga', N'Agar', N'aga@email.com', N'2018-01-12', NULL)
INSERT INTO [dbo].[User] ([Id], [PPSNo], [FirstName], [LastName], [Email], [Date], [Comments]) VALUES (29, N'7896543R', N'Mark', N'Kirwan', N'mk@mail.com', N'2018-01-31', N'Would like to do some blood tests.')
SET IDENTITY_INSERT [dbo].[User] OFF
